[package]
name = "shuttle-demo-ledoyen"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-axum = "0.24.0"
shuttle-runtime = "0.24.0"
shuttle-secrets = "0.24.0"
axum = "0.6.20"
tokio = "1.32.0"
anyhow = "1.0.75"
tracing = "0.1.37"
