name: Deploy to Shuttle.rs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ledoyen/deploy-action@feature/idiomatic_secret_input
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          allow-dirty: "true"
          secrets: |
            SECRET_1 = '${{ secrets.SECRET_1 }}'
            SECRET_2 = '${{ secrets.SECRET_2 }}'
            NOT_A_SECRET = 'Shuttle rocks'
